/**
 * Cleans the commit message generated by AI providers.
 * Removes markdown code blocks, quotes, and common prefixes.
 */
export function cleanCommitMessage(message: string): string {
    if (!message) {
        return "";
    }

    let cleaned = message.trim();

    // Remove markdown code blocks (```json, ```, etc)
    // Handle cases where the code block might wrap the whole message
    cleaned = cleaned.replace(/^```[a-z]*\s*/i, "").replace(/\s*```$/, "");

    // Remove inline code blocks if the whole message is wrapped in them
    if (cleaned.startsWith("`") && cleaned.endsWith("`")) {
        cleaned = cleaned.substring(1, cleaned.length - 1);
    }

    // Remove quotes
    cleaned = cleaned.replace(/^["']|["']$/g, "");

    // Remove newlines and excess whitespace (commit message should be single line mostly, or at least trimmed)
    cleaned = cleaned.replace(/[\r\n]+/g, " ");

    // Remove common prefixes often hallucinated by AI
    cleaned = cleaned.replace(
        /^(text|commit|git|output|message|suggestion)\s*[:]?\s*/i,
        ""
    );

    return cleaned.trim();
}
